github: Add Check go mod tidy step to ci-lint workflow

diff --git a/.github/workflows/ci-lint.yml b/.github/workflows/ci-lint.yml
--- a/.github/workflows/ci-lint.yml
+++ b/.github/workflows/ci-lint.yml
@@ -37,6 +37,10 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: "12.x"
+      - name: Set up Go 1.13
+        uses: actions/setup-go@v1
+        with:
+          go-version: "1.13.x"
       - name: Install prerequisites
         run: |
           python -m pip install \
@@ -65,5 +69,18 @@ jobs:
       - name: Lint Change Log fragments
         run: |
           make lint-changelog
+        # Always run this step so that all linting errors can be seen at once.
+        if: always()
+      - name: Check go mod tidy
+        # NOTE: go mod tidy doesn't implement a check mode yet.
+        # For more details, see: https://github.com/golang/go/issues/27005.
+        run: |
+          cd go
+          go mod tidy
+          if [[ ! -z $(git status --porcelain go.mod go.sum) ]]; then
+            echo >&2 "Error: The following changes detected after running 'go mod tidy':"
+            git diff go.mod go.sum
+            exit 1
+          fi
         # Always run this step so that all linting errors can be seen at once.
         if: always()
